### ISSUE TITLE
Note from Andre about desktop environment

### ISSUE THREAD

**Issue by MatthewVita** [GoTeamEpsilon/desktop.yml#37]
"I think we should consider using MATE or XFCE as desktop environment to get most of the system"

I tend to agree. I started with Ubuntu MATE as the base but ran into some instability. I will document how to turn Ubuntu's default desktop environment into XFCE somewhere.

**Comment by MatthewVi** [comment]
@andremillet Do you think we should just include this as a link or do you want the code to install XFCE with a command line param?: https://linuxconfig.org/install-xfce-desktop-on-ubuntu-18-04-bionic-beaver-linux

**Comment by andremillet** [comment]
why not xubuntu by default? https://xubuntu.org/
I mean, I would like to be able to install the system in low to medium
hardware, to obviously reduce costs. Do you think changing desktop
environment allow it, or it doesn't make that much of difference?

*André Millet*



Em sex, 21 de set de 2018 às 12:33, mvim <notifications@github.com>
escreveu:

**Comment by andremillet** [comment]
I saw a comment on slant comparisons suggesting cinnamon as 'virtually 

> 
> 
> @andremillet Do you think we should just include this as a link on the README or do you want the code to install XFCE with a command line parameter such as `--use-xfce`?: https://linuxconfig.org/install-xfce-desktop-on-ubuntu-18-04-bionic-beaver-linux

What would differ from using xfce instead of ubuntu/unity as default?

**Comment by andremillet** [comment]
accordingly to [https://www.makeuseof.com/tag/best-lean-linux-desktop-environment-lxde-vs-xfce-vs-mate/], in terms of memory usage, both xfce and mate demands the same, so I think any of them would support the low-hardware idea

**Comment by MatthewVi** [comment]
@andremillet I think Xubuntu is a SUPERB choice.

Just updated the install notes to say:

![image](https://user-images.githubusercontent.com/1715206/45918606-74742100-be57-11e8-8586-095240cbebcc.png)

Thoughts?

**Comment by andremillet** [comment]
Live CD/USB, perhaps?

*André Millet*



Em sáb, 22 de set de 2018 às 12:06, mvim <notifications@github.com>
escreveu:

**Comment by MatthewVi** [comment]
The sites have instructions on how to install so I think we're good.

**Comment by andremillet** [comment]
I meant to provide the whole system already set.
just like a ubuntu fork

**Comment by MatthewVi** [comment]
I'm not sure how we would distribute it because the ISO file would be massive with all of the personas installed. How can we get around that?

**Comment by MatthewVi** [comment]
@andremillet Can you please edit the README to give yourself credit? You can edit the file by going here: https://github.com/GoTeamEpsilon/System/edit/master/README.md and committing the changes.

Also, here's what I'm thinking we can put (has green line in front):

![image](https://user-images.githubusercontent.com/1715206/46029372-3b3ee980-c0c1-11e8-8dc5-99f1167e6193.png)

**Comment by andremillet** [comment]
A default persona, perhaps?
Link for the specific persona [defaut] iso?

*André Millet*



Em ter, 25 de set de 2018 às 13:52, mvim <notifications@github.com>
escreveu:

**Comment by andremillet** [comment]
I have no ideia how I could give myself credit besides what you suggested.
It is fine for me

*André Millet*



Em ter, 25 de set de 2018 às 13:55, mvim <notifications@github.com>
escreveu:

**Comment by MatthewVi** [comment]
@andremillet I will put some thought into the default persona with a base install.

Also, I just added you and I to the credits section. Thanks.

**Comment by andremillet** [comment]
Great. I am waiting for xubuntu to download so I can try to install more
personas, using the preferred system. poor connection, though.
Thanks

*André Millet*



Em qui, 27 de set de 2018 às 14:07, mvim <notifications@github.com>
escreveu:
